### ISSUE TITLE
Editing with --enable-remote-edit gives error in web console

### ISSUE THREAD

**Issue by thondeboer** [streamsync-cloud/streamsync#107]
I am trying to edit and run an app INSIDE a docker container on my Ubuntu host, so need to run streamsync with this command:

```
streamsync edit testapp --host 0.0.0.0 --port 6157 --enable-remote-edit
```

And the editor shows up, with the correct UI, but any edits I try to make fail and the webconsole shows this:

```
index-3061fbab.js:1 TypeError: crypto.randomUUID is not a function
    at s (BuilderApp-2697d8a7.js:1:4812)
    at r (BuilderApp-2697d8a7.js:1:5044)
    at G (BuilderApp-2697d8a7.js:752:28118)
    at bs (index-3061fbab.js:1:16443)
    at zn (index-3061fbab.js:1:16522)
    at HTMLElement.n (index-3061fbab.js:1:73607)
```

Editing locally works fine, but I need to run my app inside the docker container which you seem to support, but editing fails for me.
Running the app seems to be OK, although I do see this pop up, but probably nothing

```
Uncaught (in promise) Error: Cannot read properties of undefined (reading '_RUNTIME_')
    at wrappedSendMessageCallback (N6YTZFOH.js:920:22)
```

**Comment by ramedina86** [comment]
Hi, apologies this needs to be handled better, it's due to the requirement of a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) by the browser.

Basically, it needs to run with `https://` or in localhost. You can also bypass this via browser configuration (in Chrome at least).

This is due to requirements of the [`crypto` API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API).

Given that this has come up repeatedly and it's frustrating, in the next release (next couple of days) **I'll add a fallback so that edition is possible in non-secure contexts**. I didn't rush to do so because I don't want to encourage this, but I think those that use the flag understand the risk.

**Comment by thondeboer** [comment]
How could I bypass this in Chrome?

**Comment by ramedina86** [comment]
The flag is discussed here https://news.ycombinator.com/item?id=20396569

**Comment by ramedina86** [comment]
Hello, in v0.2.7 the `crypto` requirement was dropped and it's now possible to edit in non-secure contexts.
