### ISSUE TITLE
Q: Event item - context in repeater component

### ISSUE THREAD

**Issue by joelwiesmann** [streamsync-cloud/streamsync#171]
Hey!

First of all: thank you for this incredible piece of software! I'm sure this project will have a bright future!

I'm using a repeater component to display data. For each item I'd like to create a button that does some action on it. Unfortunately, the payload of the click-event on the button does not feature any repeater-item context. So every button in the list will basically do the same.

Is there a way to access the "itemId" or any other way to provide context / parameters to an event?

Regards
Joel

**Comment by joelwiesmann** [comment]
Here's a visualization based on the example data. The button should remove the item from the dictionary. However right now, it doesn't know which item is being "eaten".
![image](https://github.com/streamsync-cloud/streamsync/assets/23297989/fbc2fa79-9683-4d8c-9e3b-195b9a8b205e)

**Comment by FabienArcellier** [comment]
Hi, the item called in a repeater can be accessed through a context parameter in event handler. 
Did you try this ?

```python
def item_remove(state, context):
    items = state["items"].state
    items = {k: v for k, v in items.items() if k != context["item"]}
    state["items"] = items
```

**Comment by joelwiesmann** [comment]
Hi @FabienArcellier 

Oh interesting, I wasn't aware of **context**, thanks for the hint!

I amended your example as I think context["item"] should have been context["itemId"]. Now something strange happens - the first item that is being removed properly works. When I click a second time, the state["items"] is null.

![10-11-2023_07-38-11](https://github.com/streamsync-cloud/streamsync/assets/23297989/77516860-fecf-4139-a6a1-3e98f18ce0e9)

**Comment by ramedina86** [comment]
@mmikita95 something else to look into, possibly in line with the kind of things you've been focusing on.

**Comment by mmikita95** [comment]
Having a discussion about this, we've decided to introduce a "removal" flag for keys that are carried to the frontend, so that we can track these kinds of changes in state more consistently and reliably. Basically, prepend the keys to be removed with '-', and the rest of them with '+'. This will not influence users' naming conventions, as we'll only track the first character for this flag, which will be added during the preparation of mutations. I'll be working on this on the backend's side now.
