### ISSUE TITLE
Reactive watcher sometimes not getting event

### ISSUE THREAD

**Issue by aleloi** [streamsync-cloud/streamsync#172]
Hi, I'm setting up a custom login component to use in streamsync. I want persistent logins, so I have to keep some client state like cookies. Otherwise streamsync state gets reset when I reload the page.

I've added a field that looks like this and connected it to `@{session_cookie}`

```js
streamsync.fields.cookie = {
    name: "Secret Session Cookie",
    init: "",
    type: FieldType.Text,
}
```
To set the cookie, I have this watcher:
```ts
watch(() => fields.cookie.value, (new_value) => {
   if (new_value !== "") {
      console.log("Setting auth cookie!");
      document.cookie = new_value;
   }
});
```

Then changing the state in the client code should trigger the watcher. It does, but only if I add a `sleep()` before changing the page:
```python
if valid(user, password):
    state["session_cookie"] = f"login_cookie={cookie}; SameSite=Lax"

    # Doesn't work without this sleep!
    time.sleep(1)
    state["logged_in"] = True
    state.set_page("main_page")
```

My login component is on a separate page from the rest of the app. After successfully logging in, I want to switch to `main_page`.

My questions are: is this a bug? Or a limitation in Vue / Vite? Am I using a convoluted way to set a cookie?

**Comment by ramedina86** [comment]
When you include the `time.sleep(1)` Streamsync sends a partial state update, and your component gets to react because it's still there. A second after, the page is switched.

If you don't include a sleep, **all mutations are processed at the same time**, including the page switch. This is because sending them one by one and waiting for the DOM to react would be very slow. This behaviour is documented under  [Event handlers](https://www.streamsync.cloud/event-handlers.html#execution-flow).

The page switch destroys the component. I believe you could include your custom component in the main page (perhaps hidden?) and use a [Vue Eager Watcher](https://vuejs.org/guide/essentials/watchers.html#eager-watchers) i.e. `{ immediate: true }` to make sure the watcher runs as soon as the page loads.

I wouldn't call it a Streamsync bug or a Vue limitation, just a rather advanced use case that requires in-depth knowledge about both.
