### ISSUE TITLE
Python 3.12 tests issuing DeprecationWarning related to multiprocessing

### ISSUE THREAD

**Issue by ramedina86** [streamsync-cloud/streamsync#227]
`test_app_runner.py::TestAppRunner::test_code_update
  /usr/local/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=92883) is multi-threaded, use of fork() may lead to deadlocks in the child.
    self.pid = os.fork()`

@mmikita95 seems closely related to what you're working on this week, please have a look

**Comment by mmikita95** [comment]
I tried running this test on Python 3.12.1, macOS Sonoma 14.3 (M1 chip), and there is no such warning displayed for me. Is there maybe some additional info you could provide about this issue?

I must say that when I was setting up a new 3.12.1 environment (as mine was on 3.10), I've ran into issues with installing pyarrow-12.0.0/12.0.1, so I used Fabien's poetry setup to try to bypass it (successfully), and noticed that it installed a newer version, 15.0.0. I imagine this issue could be happening due to one of our dependencies, and I might've solved it unknowingly installing a newer version for it too.
