### ISSUE TITLE
Message don't works with combined with repeater

### ISSUE THREAD

**Issue by lincoln2491** [streamsync-cloud/streamsync#43]
I tried to use the 'repeater' component with the 'message' component inside. My goal is to set the visibility of the message based on variables in the state dictionary, but it doesn't work.

I have attempted different approaches to set the visibility, but none of them have worked.

I have attached the full code for reproduction.
[test.zip](https://github.com/streamsync-cloud/streamsync/files/11870303/test.zip)

**Comment by eliorc** [comment]
Can confirm, I too try to set the visibility using custom attributes and fail.

This is my element structure, at the bottom are the buttons which their visibility cannot be set using custom attribute
![image](https://github.com/streamsync-cloud/streamsync/assets/17727283/15a0ec5d-55b9-410c-9a2a-91744eedfa18)

**Comment by ramedina86** [comment]
Hi both, thanks for reporting this.

It's _technically_ expected behaviour, as right now Visibility requires a state element (which is different from a context element generated by a _Repeater_).

That being said, you made me realise that it was a significant and unnecessary limitation, plus potentially confusing. I've changed this to accept both state and context and will release it in the new version.

**Comment by lincoln2491** [comment]
Hi @ramedina86  

Thanks for the help and info. Wish you good luck in future works with streamsync :)

**Comment by ramedina86** [comment]
This was updated in the latest release 0.1.9, which accepts both state and context (i.e. `item` and `itemId` from _Repeater_). Thanks for bringing this up.
