### ISSUE TITLE
Automatically refresh image container when source changes

### ISSUE THREAD

**Issue by hidara2000** [streamsync-cloud/streamsync#44]
Hi, 
Firstly thank you so much for creating this!! Excellent work.

Is there any way to trigger refreshing an image container if the link or photo changes? I have two instances where this would be ideal:

1.  I am grabbing an image from a security camera every 10 secs and copying it to the static folder (static/current_photo.jpg). I'm hoping to always display the most current image without forcing a page refresh.
2.  I have a dropdown list of image paths but when I choose a new image and update the state with the new location, I have to refresh the page to see the selected image

Interestingly for the second option, if I'm in the "user interface" tab in builder and I click on the image it refreshes correctly. This doesn't happen when deployed.

Thanks again and any help would be appreciated. Great work!!!

**Comment by ramedina86** [comment]
Hi, I'm glad to hear you like Streamsync!

Thanks a lot for reporting this, I've done some checks on the second point and it's a bug affecting the refresh of the _Image_ component specifically.

I'll fix it for the next release, which I expect to release within the next week. Until then, you can include the path in the caption which should trigger a refresh of the image.

**Comment by hidara2000** [comment]
Perfect, thanks again for your work!

**Comment by ramedina86** [comment]
This has been fixed in 0.1.9, which was just released. Thanks for reporting it!

By the way, regarding your first point, to force the reload of the same path you can save a counter in state and add it to the path (in the querystring) so that the browser invalidates the cache. The path would look something like `static/current_photo.jpg?@{counter}`. Given that the bug affected image refresh in general, you'll need the new version for this to work as expected.

**Comment by hidara2000** [comment]
Cheers
