### ISSUE TITLE
A question about interacting with the selected region of a graph

### ISSUE THREAD

**Issue by nxixi** [streamsync-cloud/streamsync#50]
Hello, 
    StreamSync is indeed a very useful visualization tool! 
    I encountered an issue while using StreamSync: I want to change the color (or perform other interactions) of the data within the selected region when displaying a graph using the Plotly Graph tool. I tried using scatter.on_selection(selection_fn) and defined the selection_fn function to change the color of the selected region. This method worked successfully in the notebook, but it doesn't achieve the desired effect in StreamSync. Can StreamSync achieve the effect I want, and how should I adjust the code?
<img width="762" alt="image" src="https://github.com/streamsync-cloud/streamsync/assets/39615466/735afda4-334d-409e-a076-4d0187e770c1">

**Comment by ramedina86** [comment]
Hi nxixi, unfortunately this isn't yet supported. I'm not sure it's viable since the renderer used by Plotly differs in terms of notebook and browser.

If anyone knows whether this is supported in any non-notebook solution, I'd appreciate if you can point me to it so I can have a look and understand how to solve this challenge. I checked Streamlit, but I believe they're also lacking this capability.

**Comment by ramedina86** [comment]
Hi, sharing this update for anyone who might be interested in this.

It's now possible to listen to Plotly events (click, selection and deselection) using Streamsync events. This differs from `on_click`, `on_selection` as these are for notebook widgets.  

<img width="228" alt="Screenshot 2023-09-04 at 11 31 05" src="https://github.com/streamsync-cloud/streamsync/assets/64783088/1d914e72-c3f4-4029-9779-ed63879166ad">

https://github.com/streamsync-cloud/streamsync/assets/64783088/de6ee1fc-788a-4379-9d30-2169b62259e1
