### ISSUE TITLE
Pydantic 2

### ISSUE THREAD

**Issue by wilstrup** [streamsync-cloud/streamsync#63]
Do you have a timeline to migrate to pydantic 2? I am using a package that recently migrated, so now I am deadlocked,

**Comment by ramedina86** [comment]
I've identified the issue, it's due to a regression in Pydantic 2 related to `numpy.float64` values.

[https://github.com/pydantic/pydantic/issues/6963](https://github.com/pydantic/pydantic/issues/6963) 

I'll see how this evolves but I've already come up with a fix by converting `numpy.float64` to built-in float during serialisation time.

There doesn't seem to be any other issues so migration to Pydantic 2 will be completed for the next release (in 1-2 weeks).

**Comment by ramedina86** [comment]
Pydantic 2 is used in v0.1.12, which was just released.
