### ISSUE TITLE
Custom dataframe formatting (e.g. wrap text in cell)

### ISSUE THREAD

**Issue by lambertchu** [streamsync-cloud/streamsync#67]
Thank you for your awesome work on this tool!

Is there any functionality to apply more flexible, custom styling on dataframe elements?

More specifically, I am looking to apply text wrapping on a dataframe column so that very long strings are completely visible in the column's cells. At the moment, the string is not completely visible if it exceeds the max width of the column.

**Comment by samgarvis** [comment]
> Thank you for your awesome work on this tool!
> 
> Is there any functionality to apply more flexible, custom styling on dataframe elements?
> 
> More specifically, I am looking to apply text wrapping on a dataframe column so that very long strings are completely visible in the column's cells. At the moment, the string is not completely visible if it exceeds the max width of the column.

Also, is there any documentation on testing out changes to this repo locally? I would like to contribute, but I'm having trouble spinning this up locally

**Comment by ramedina86** [comment]
Hey @lambertchu and @samgarvis, thank you for using Streamsync and taking the time to share your thoughts. I'm glad you're enjoying it (minus this, I guess!). 

After taking a look at this issue, I've developed a wrap/no-wrap flag. An example (using mock data) is shown below.

<img width="1149" alt="sc1" src="https://github.com/streamsync-cloud/streamsync/assets/64783088/9604719f-4935-4f0c-a7ad-f8a3d1e055ab">

There's currently one limitation, which is that scrolling jumps row by row. So if there's a cell that's taller than the grid, the bottom of the cell won't be visible. 

There's a change that was necessary to make, which is allowing the row offset to go down to the last row, see below.

<img width="1153" alt="sc2" src="https://github.com/streamsync-cloud/streamsync/assets/64783088/9ae1fb66-f345-467b-8460-95ab0d447c5a">

I hope this is aligned with your use cases. I expect to release it this weekend together with a number of other features.

@samgarvis I worked on a `CONTRIBUTING.md` file that gives some hints on creating a local dev environment. I haven't merged yet but it's on the dev branch if you want to check that out.

---

PS: *Dataframe* behaves differently than other elements because it renders only the rows required to avoid overwhelming the DOM, which is quite easy with as little as 1k rows. So it's creating/destroying elements on demand as you scroll. This means that you cannot know the height of the whole grid beforehand, unless you used a fixed height and say I have 10 rows, so it's 360px. This is because, realistically, you can only know after rendering.

**Comment by samgarvis** [comment]
Dude, you are the goat!
Thank you so much for addressing this so soon.
Streamsync really is an amazing product🙏🫡

**Comment by lambertchu** [comment]
Thank you for the update and quick response @ramedina86!!

**Comment by ramedina86** [comment]
Available in v0.1.12, which was just released.
